"""empty message

Revision ID: 156bd4812db4
Revises: 
Create Date: 2021-12-15 18:31:24.363969

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '156bd4812db4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('adress', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('numberDocumentation', sa.String(length=120), nullable=True),
    sa.Column('typeDocumentation', sa.String(length=10), nullable=True),
    sa.Column('postalCode', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_data')
    # ### end Alembic commands ###
