"""empty message

Revision ID: 4ce3d631f36a
Revises: 156bd4812db4
Create Date: 2021-12-15 18:52:48.124435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce3d631f36a'
down_revision = '156bd4812db4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_data', sa.Column('password', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_data', 'password')
    # ### end Alembic commands ###
