"""empty message

Revision ID: 9b1828ca9f75
Revises: 4b631885ec92
Create Date: 2021-12-21 17:24:29.835175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b1828ca9f75'
down_revision = '4b631885ec92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userdata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('surname', sa.String(length=120), nullable=False),
    sa.Column('adress', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=False),
    sa.Column('numberDocumentation', sa.String(length=120), nullable=False),
    sa.Column('typeDocumentation', sa.String(length=120), nullable=False),
    sa.Column('postalCode', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('client',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('nif', sa.String(length=50), nullable=False),
    sa.Column('address', sa.String(length=50), nullable=False),
    sa.Column('postalCode', sa.Integer(), nullable=False),
    sa.Column('userData_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['userData_id'], ['userdata.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tax', sa.Integer(), nullable=False),
    sa.Column('discount', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('product',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('producttobill',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bill.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_data')
    op.add_column('supplier', sa.Column('userData_id', sa.Integer(), nullable=False))
    op.alter_column('supplier', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
    op.alter_column('supplier', 'phoneNumber',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.create_unique_constraint(None, 'supplier', ['address'])
    op.create_unique_constraint(None, 'supplier', ['postalCode'])
    op.create_unique_constraint(None, 'supplier', ['nif'])
    op.create_foreign_key(None, 'supplier', 'userdata', ['userData_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'supplier', type_='foreignkey')
    op.drop_constraint(None, 'supplier', type_='unique')
    op.drop_constraint(None, 'supplier', type_='unique')
    op.drop_constraint(None, 'supplier', type_='unique')
    op.alter_column('supplier', 'phoneNumber',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('supplier', 'email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
    op.drop_column('supplier', 'userData_id')
    op.create_table('user_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('adress', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('company', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('numberDocumentation', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('typeDocumentation', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('postalCode', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_data_pkey')
    )
    op.drop_table('producttobill')
    op.drop_table('product')
    op.drop_table('bill')
    op.drop_table('client')
    op.drop_table('userdata')
    # ### end Alembic commands ###
