"""empty message

Revision ID: c0037de6700d
Revises: 
Create Date: 2022-01-15 12:18:48.511898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0037de6700d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'number',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bill', 'number',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
